# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/models.tabpfnts.ipynb.

# %% auto 0
__all__ = ['TabPFNTS']

# %% ../../nbs/models.tabpfnts.ipynb 5
import torch
import numpy as np
import pandas as pd
from typing import Optional, List

from ..common._base_model import BaseModel
from ..losses.pytorch import MAE

try:
    from tabpfn_time_series import TabPFNTimeSeriesPredictor, TabPFNMode
    from tabpfn_time_series.data_preparation import to_gluonts_univariate, generate_test_X
    from tabpfn_time_series import FeatureTransformer
    from tabpfn_time_series.features import (
        RunningIndexFeature,
        CalendarFeature,
        AutoSeasonalFeature,
    )
    from autogluon.timeseries import TimeSeriesDataFrame
    _tabpfn_available = True
except ImportError:
    print("TabPFN Time Series not installed. Please install with: pip install tabpfn-time-series")
    TabPFNTimeSeriesPredictor = None
    TabPFNMode = None
    _tabpfn_available = False

# %% ../../nbs/models.tabpfnts.ipynb 6
class TabPFNTS(BaseModel):
    """TabPFNTS

    TabPFN Time Series model wrapper for NeuralForecast.
    This model uses the TabPFN architecture specifically designed for time series forecasting.
    TabPFN leverages in-context learning capabilities without requiring traditional training.

    **Parameters:**<br>
    `h`: int, forecast horizon.<br>
    `input_size`: int, considered autorregresive inputs (lags), y=[1,2,3,4] input_size=2 -> lags=[1,2].<br>
    `context_length`: int=4096, maximum context length for TabPFN model.<br>
    `tabpfn_mode`: TabPFNMode=None, mode for TabPFN operation (LOCAL, REMOTE, etc.).<br>
    `debug`: bool=False, enable debug mode for additional logging.<br>
    `stat_exog_list`: str list, static exogenous columns.<br>
    `hist_exog_list`: str list, historic exogenous columns.<br>
    `futr_exog_list`: str list, future exogenous columns.<br>
    `exclude_insample_y`: bool=False, the model skips the autoregressive features y[t-input_size:t] if True.<br>
    `loss`: PyTorch module, instantiated train loss class from [losses collection](https://nixtla.github.io/neuralforecast/losses.pytorch.html).<br>
    `valid_loss`: PyTorch module=`loss`, instantiated valid loss class from [losses collection](https://nixtla.github.io/neuralforecast/losses.pytorch.html).<br>
    `max_steps`: int=1, maximum number of training steps.<br>
    `learning_rate`: float=1e-3, Learning rate between (0, 1).<br>
    `num_lr_decays`: int=-1, Number of learning rate decays, evenly distributed across max_steps.<br>
    `early_stop_patience_steps`: int=-1, Number of validation iterations before early stopping.<br>
    `val_check_steps`: int=100, Number of training steps between every validation loss check.<br>
    `batch_size`: int=32, number of different series in each batch.<br>
    `valid_batch_size`: int=None, number of different series in each validation and test batch, if None uses batch_size.<br>
    `windows_batch_size`: int=1024, number of windows to sample in each training batch, default uses all.<br>
    `inference_windows_batch_size`: int=-1, number of windows to sample in each inference batch, -1 uses all.<br>
    `start_padding_enabled`: bool=False, if True, the model will pad the time series with zeros at the beginning, by input size.<br>
    `step_size`: int=1, step size between each window of temporal data.<br>
    `scaler_type`: str='identity', type of scaler for temporal inputs normalization see [temporal scalers](https://nixtla.github.io/neuralforecast/common.scalers.html).<br>
    `random_seed`: int=1, random_seed for pytorch initializer and numpy generators.<br>
    `drop_last_loader`: bool=False, if True `TimeSeriesDataLoader` drops last non-full batch.<br>
    `alias`: str, optional,  Custom name of the model.<br>
    `optimizer`: Subclass of 'torch.optim.Optimizer', optional, user specified optimizer instead of the default choice (Adam).<br>
    `optimizer_kwargs`: dict, optional, list of parameters used by the user specified `optimizer`.<br>
    `lr_scheduler`: Subclass of 'torch.optim.lr_scheduler.LRScheduler', optional, user specified lr_scheduler instead of the default choice (StepLR).<br>
    `lr_scheduler_kwargs`: dict, optional, list of parameters used by the user specified `lr_scheduler`.<br>
    `dataloader_kwargs`: dict, optional, list of parameters passed into the PyTorch Lightning dataloader by the `TimeSeriesDataLoader`. <br>
    `**trainer_kwargs`: int,  keyword trainer arguments inherited from [PyTorch Lighning's trainer](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html?highlight=trainer).<br>

    **References:**<br>
    - [TabPFN: A Transformer that Solves Small Tabular Classification Problems in a Second](https://arxiv.org/abs/2207.01848)<br>
    """

    # Model capabilities
    EXOGENOUS_FUTR = True   # Enable future exogenous variables support
    EXOGENOUS_HIST = True   # Enable historical exogenous variables support  
    EXOGENOUS_STAT = True   # Enable static exogenous variables support
    MULTIVARIATE = False    # TabPFNTS is univariate
    RECURRENT = False       # TabPFNTS is direct forecasting

    def __init__(
        self,
        h: int,
        input_size: int,
        context_length: int = 4096,
        tabpfn_mode: Optional[object] = None,
        debug: bool = False,
        stat_exog_list: Optional[List[str]] = None,
        hist_exog_list: Optional[List[str]] = None,
        futr_exog_list: Optional[List[str]] = None,
        exclude_insample_y: bool = False,
        loss=MAE(),
        valid_loss=None,
        max_steps: int = 1,
        learning_rate: float = 1e-3,
        num_lr_decays: int = -1,
        early_stop_patience_steps: int = -1,
        val_check_steps: int = 100,
        batch_size: int = 32,
        valid_batch_size: Optional[int] = None,
        windows_batch_size: int = 1024,
        inference_windows_batch_size: int = -1,
        start_padding_enabled: bool = False,
        step_size: int = 1,
        scaler_type: str = "identity",
        random_seed: int = 1,
        drop_last_loader: bool = False,
        alias: Optional[str] = None,
        optimizer=None,
        optimizer_kwargs=None,
        lr_scheduler=None,
        lr_scheduler_kwargs=None,
        dataloader_kwargs=None,
        **trainer_kwargs
    ):
        
        # Check TabPFN availability
        if not _tabpfn_available:
            raise ImportError(
                "TabPFN Time Series not installed. Please install with: pip install tabpfn-time-series"
            )

        # Initialize base model
        super().__init__(
            h=h,
            input_size=input_size,
            stat_exog_list=stat_exog_list,
            hist_exog_list=hist_exog_list,
            futr_exog_list=futr_exog_list,
            exclude_insample_y=exclude_insample_y,
            loss=loss,
            valid_loss=valid_loss,
            max_steps=max_steps,
            learning_rate=learning_rate,
            num_lr_decays=num_lr_decays,
            early_stop_patience_steps=early_stop_patience_steps,
            val_check_steps=val_check_steps,
            batch_size=batch_size,
            valid_batch_size=valid_batch_size,
            windows_batch_size=windows_batch_size,
            inference_windows_batch_size=inference_windows_batch_size,
            start_padding_enabled=start_padding_enabled,
            step_size=step_size,
            scaler_type=scaler_type,
            random_seed=random_seed,
            drop_last_loader=drop_last_loader,
            alias=alias,
            optimizer=optimizer,
            optimizer_kwargs=optimizer_kwargs,
            lr_scheduler=lr_scheduler,
            lr_scheduler_kwargs=lr_scheduler_kwargs,
            dataloader_kwargs=dataloader_kwargs,
            **trainer_kwargs
        )
        
        # TabPFNTS specific parameters
        self.context_length = context_length
        self.tabpfn_mode = tabpfn_mode if tabpfn_mode is not None else (TabPFNMode.LOCAL if TabPFNMode else None)
        self.debug = debug
        
        # Initialize TabPFN predictor
        if _tabpfn_available:
            self.predictor = TabPFNTimeSeriesPredictor(
                tabpfn_mode=self.tabpfn_mode,
            )
        else:
            self.predictor = None
        
        # Initialize prediction cache
        self._prediction_cache = {}
        
        if self.debug:
            print(f"TabPFNTS initialized with:")
            print(f"  - Horizon: {self.h}")
            print(f"  - Input size: {self.input_size}")
            print(f"  - Context length: {self.context_length}")
            print(f"  - TabPFN mode: {self.tabpfn_mode}")
            print(f"  - TabPFN available: {_tabpfn_available}")
            print(f"  - Exogenous support: hist={len(self.hist_exog_list)}, stat={len(self.stat_exog_list)}, futr={len(self.futr_exog_list)}")

    def fit(self, dataset, val_size=0, test_size=0, random_seed=None, distributed_config=None):
        """
        TabPFNTS doesn't require traditional training as it uses in-context learning.
        This method is provided for compatibility with NeuralForecast's interface.
        """
        if self.debug:
            print("TabPFNTS: No training required - using in-context learning")
        
        self.val_size = val_size
        self.test_size = test_size
        self._fitted = True
        return self

    def training_step(self, batch, batch_idx):
        """
        Dummy training step for PyTorch Lightning compatibility.
        TabPFNTS doesn't require training.
        """
        # Return minimal loss to satisfy PyTorch Lightning
        return torch.tensor(0.0, requires_grad=True)

    def validation_step(self, batch, batch_idx):
        """
        Dummy validation step for PyTorch Lightning compatibility.
        """
        return torch.tensor(0.0)

    def forward(self, windows_batch):
        """
        Forward pass for TabPFNTS using in-context learning.
        This is called by predict_step during cross-validation.
        """
        # Extract input data
        insample_y = windows_batch["insample_y"]  # [batch_size, input_size, 1]
        hist_exog = windows_batch["hist_exog"]    # [batch_size, input_size, hist_exog_size]
        futr_exog = windows_batch["futr_exog"]    # [batch_size, input_size + h, futr_exog_size]  
        stat_exog = windows_batch["stat_exog"]    # [batch_size, stat_exog_size]
        
        batch_size = insample_y.shape[0]
        
        if self.debug:
            print(f"TabPFNTS forward: batch_size={batch_size}, insample_y.shape={insample_y.shape}")
            if hist_exog is not None:
                print(f"TabPFNTS forward: hist_exog.shape={hist_exog.shape}")
            if futr_exog is not None:
                print(f"TabPFNTS forward: futr_exog.shape={futr_exog.shape}")
            if stat_exog is not None:
                print(f"TabPFNTS forward: stat_exog.shape={stat_exog.shape}")
        
        # Initialize predictions array
        predictions = torch.zeros(batch_size, self.h, self.loss.outputsize_multiplier, 
                                 device=insample_y.device, dtype=insample_y.dtype)
        
        # Process each window in the batch
        for i in range(batch_size):
            series_data = insample_y[i, :, 0]  # [input_size]
            
            # Extract exogenous data for this window
            hist_exog_data = None
            if hist_exog is not None:
                hist_exog_data = hist_exog[i].detach().cpu().numpy()  # [input_size, hist_exog_size]
            
            futr_exog_data = None
            if futr_exog is not None:
                futr_exog_data = futr_exog[i].detach().cpu().numpy()  # [input_size + h, futr_exog_size]
            
            stat_exog_data = None
            if stat_exog is not None:
                stat_exog_data = stat_exog[i].detach().cpu().numpy()  # [stat_exog_size]
            
            # Check for valid data
            valid_mask = ~torch.isnan(series_data)
            if not valid_mask.any():
                # No valid data, predictions remain zero
                continue
                
            # Find last valid index and convert to numpy
            valid_indices = valid_mask.nonzero().flatten()
            if len(valid_indices) == 0:
                continue
                
            last_valid_idx = valid_indices[-1].item()
            train_data = series_data[:last_valid_idx+1].detach().cpu().numpy()
            
            # Prepare exogenous data aligned with valid target data
            exog_features = self._prepare_exogenous_features(
                train_data, hist_exog_data, futr_exog_data, stat_exog_data, 
                last_valid_idx, i
            )
            
            # Truncate data to fit within TabPFN's context window
            truncated_data, truncated_exog = self._truncate_context_with_exog(train_data, exog_features)
            
            if self.debug and i == 0:  # Only print for first window to avoid spam
                print(f"TabPFNTS forward: window {i}, valid data length={len(train_data)}, truncated length={len(truncated_data)}")
                if truncated_exog is not None:
                    print(f"TabPFNTS forward: exogenous features shape={truncated_exog.shape}")
            
            # Only proceed if we have enough data
            if len(truncated_data) < 2:
                # Use simple naive forecast
                if len(truncated_data) > 0:
                    naive_forecast = truncated_data[-1]
                else:
                    naive_forecast = 0.0
                predictions[i, :, 0] = naive_forecast
                continue
                
            try:
                # Make prediction using TabPFN with exogenous variables
                series_predictions = self._make_tabpfn_prediction_with_exog(
                    truncated_data, truncated_exog, futr_exog_data, stat_exog_data, i
                )
                
                # Convert back to tensor
                pred_tensor = torch.tensor(series_predictions, dtype=insample_y.dtype, device=insample_y.device)
                predictions[i, :, 0] = pred_tensor
                
            except Exception as e:
                if self.debug:
                    print(f"TabPFNTS forward failed for window {i}: {e}")
                # If TabPFN fails, use simple naive forecast
                if len(truncated_data) >= 5:
                    naive_forecast = np.mean(truncated_data[-5:])
                elif len(truncated_data) > 0:
                    naive_forecast = np.mean(truncated_data)
                else:
                    naive_forecast = 0.0
                predictions[i, :, 0] = naive_forecast
        
        return predictions

    def _prepare_exogenous_features(self, train_data, hist_exog_data, futr_exog_data, stat_exog_data, last_valid_idx, window_idx):
        """
        Prepare exogenous features for TabPFN prediction.
        Combines historical, future, and static exogenous variables into a feature matrix.
        """
        n_train = len(train_data)
        features_list = []
        
        # Add historical exogenous variables (aligned with target data)
        if hist_exog_data is not None and self.hist_exog_size > 0:
            # Use only the valid historical exogenous data
            hist_features = hist_exog_data[:last_valid_idx+1]  # [n_train, hist_exog_size]
            if len(hist_features) == n_train:
                features_list.append(hist_features)
            elif self.debug:
                print(f"Warning: historical exog length mismatch for window {window_idx}")
        
        # Add static exogenous variables (repeated for each time step)  
        if stat_exog_data is not None and self.stat_exog_size > 0:
            # Repeat static features for each time step
            static_features = np.tile(stat_exog_data, (n_train, 1))  # [n_train, stat_exog_size]
            features_list.append(static_features)
        
        # Add future exogenous variables for the historical period
        if futr_exog_data is not None and self.futr_exog_size > 0:
            # Use future exogenous data corresponding to the historical period
            futr_hist_features = futr_exog_data[:last_valid_idx+1]  # [n_train, futr_exog_size]
            if len(futr_hist_features) == n_train:
                features_list.append(futr_hist_features)
            elif self.debug:
                print(f"Warning: future exog length mismatch for window {window_idx}")
        
        # Combine all features
        if features_list:
            exog_features = np.concatenate(features_list, axis=1)  # [n_train, total_exog_size]
            return exog_features
        else:
            return None

    def _truncate_context_with_exog(self, y_values, exog_features):
        """
        Truncate time series data and exogenous features to fit within TabPFN's context window.
        Uses the most recent data points.
        """
        if len(y_values) <= self.context_length:
            return y_values, exog_features
            
        # Use the most recent data points
        truncated_data = y_values[-self.context_length:]
        
        # Truncate exogenous features correspondingly
        truncated_exog = None
        if exog_features is not None:
            truncated_exog = exog_features[-self.context_length:]
            
        if self.debug:
            print(f"Truncated series from {len(y_values)} to {len(truncated_data)} points")
            if exog_features is not None:
                print(f"Truncated exog from {len(exog_features)} to {len(truncated_exog)} points")
        
        return truncated_data, truncated_exog

    def _truncate_context(self, y_values):
        """
        Truncate time series data to fit within TabPFN's context window.
        Uses the most recent data points.
        (Kept for backward compatibility)
        """
        truncated_data, _ = self._truncate_context_with_exog(y_values, None)
        return truncated_data

    def _make_tabpfn_prediction_with_exog(self, y_values, exog_features, futr_exog_data, stat_exog_data, window_idx):
        """
        Make prediction using TabPFN for a single time series with exogenous variables.
        This integrates exogenous variables into the TabPFN prediction process.
        """
        try:
            # Create input data combining target and exogenous variables
            if exog_features is not None:
                # Combine target and exogenous features
                input_data = self._create_tabpfn_input(y_values, exog_features, futr_exog_data, stat_exog_data)
            else:
                # Fall back to target-only prediction
                input_data = y_values.reshape(-1, 1)
            
            # Use actual TabPFN prediction if available, otherwise use enhanced heuristic
            predictions = self._tabpfn_predict_with_features(input_data, y_values, exog_features, window_idx)
            
            return predictions
            
        except Exception as e:
            if self.debug:
                print(f"TabPFN prediction with exog error for window {window_idx}: {e}")
            # Fallback to simple prediction
            return self._make_tabpfn_prediction(y_values)

    def _create_tabpfn_input(self, y_values, exog_features, futr_exog_data, stat_exog_data):
        """
        Create input matrix for TabPFN that combines target and exogenous variables.
        """
        n_points = len(y_values)
        
        # Start with target values
        input_matrix = [y_values.reshape(-1, 1)]
        
        # Add historical exogenous features (already prepared)
        if exog_features is not None:
            input_matrix.append(exog_features)
        
        # Combine all features
        combined_input = np.concatenate(input_matrix, axis=1)  # [n_points, 1 + total_exog_size]
        
        return combined_input

    def _tabpfn_predict_with_features(self, input_data, y_values, exog_features, window_idx):
        """
        Make TabPFN prediction using the combined input data with real TabPFN API.
        This integrates with the actual TabPFN time series predictor.
        """
        try:
            if not _tabpfn_available or self.predictor is None:
                if self.debug:
                    print(f"TabPFN not available, falling back to heuristic for window {window_idx}")
                return self._make_tabpfn_prediction_fallback(input_data, y_values)
            
            # Create TimeSeriesDataFrame for TabPFN
            train_tsdf = self._create_tabpfn_dataframe(y_values, exog_features, window_idx)
            
            # Generate test periods for prediction
            test_tsdf = generate_test_X(train_tsdf, self.h)
            
            # Apply feature transformation
            feature_transformer = self._create_feature_transformer()
            train_tsdf_transformed, test_tsdf_transformed = feature_transformer.transform(
                train_tsdf, test_tsdf
            )
            
            # Make prediction with TabPFN
            pred_tsdf = self._predict_with_tabpfn(
                train_tsdf_transformed, test_tsdf_transformed, window_idx
            )
            
            # Extract and process predictions
            predictions = self._extract_tabpfn_predictions(pred_tsdf, y_values)
            
            if self.debug and window_idx == 0:
                print(f"TabPFN prediction successful for window {window_idx}, shape: {predictions.shape}")
            
            return predictions
            
        except Exception as e:
            if self.debug:
                print(f"TabPFN prediction error for window {window_idx}: {e}")
            # Fall back to enhanced heuristic
            return self._make_tabpfn_prediction_fallback(input_data, y_values)

    def _create_tabpfn_dataframe(self, y_values, exog_features, window_idx):
        """
        Create TimeSeriesDataFrame for TabPFN with exogenous variables.
        """
        n_points = len(y_values)
        
        # Create timestamps (TabPFN needs proper datetime index)
        timestamps = pd.date_range(start='2020-01-01', periods=n_points, freq='5T')
        
        # Base dataframe with target values
        data_dict = {
            'item_id': f'series_{window_idx}',
            'timestamp': timestamps,
            'target': y_values
        }
        
        # Add exogenous features if available
        if exog_features is not None and exog_features.shape[1] > 0:
            # Add historical exogenous variables
            if self.hist_exog_size > 0:
                hist_end_idx = self.hist_exog_size
                for i, col_name in enumerate(self.hist_exog_list):
                    if i < hist_end_idx and i < exog_features.shape[1]:
                        data_dict[col_name] = exog_features[:, i]
            
            # Add static exogenous variables (repeated for each time step)
            if self.stat_exog_size > 0:
                stat_start_idx = self.hist_exog_size
                for i, col_name in enumerate(self.stat_exog_list):
                    col_idx = stat_start_idx + i
                    if col_idx < exog_features.shape[1]:
                        # Static features are already repeated in exog_features
                        data_dict[col_name] = exog_features[:, col_idx]
        
        # Create DataFrame
        train_df = pd.DataFrame(data_dict)
        
        # Convert to AutoGluon TimeSeriesDataFrame
        train_tsdf = TimeSeriesDataFrame.from_data_frame(
            train_df, id_column="item_id", timestamp_column="timestamp"
        )
        
        return train_tsdf

    def _create_feature_transformer(self):
        """
        Create feature transformer for TabPFN with appropriate features.
        """
        # Use standard time series features that work well with TabPFN
        selected_features = [
            RunningIndexFeature(),
            CalendarFeature(),
            AutoSeasonalFeature(),
        ]
        
        return FeatureTransformer(selected_features)

    def _predict_with_tabpfn(self, train_tsdf_transformed, test_tsdf_transformed, window_idx):
        """
        Make prediction with TabPFN predictor, handling context limits.
        """
        try:
            # First attempt with normal settings
            pred_tsdf = self.predictor.predict(
                train_tsdf_transformed, test_tsdf_transformed
            )
            return pred_tsdf
            
        except Exception as tabpfn_error:
            error_msg = str(tabpfn_error)
            
            # Handle context limit errors
            if "greater than the maximum number of samples" in error_msg:
                if self.debug:
                    print(f"Context limit exceeded for window {window_idx}, retrying with ignore_pretraining_limits=True")
                
                pred_tsdf = self.predictor.predict(
                    train_tsdf_transformed, test_tsdf_transformed,
                    ignore_pretraining_limits=True
                )
                return pred_tsdf
            else:
                # Re-raise other errors
                raise tabpfn_error

    def _extract_tabpfn_predictions(self, pred_tsdf, y_values):
        """
        Extract predictions from TabPFN result and ensure proper shape.
        """
        pred_values = pred_tsdf['target'].values
        
        if len(pred_values) >= self.h:
            # Use the first h predictions
            predictions = pred_values[:self.h]
        else:
            # Pad with last prediction if needed
            predictions = np.zeros(self.h)
            predictions[:len(pred_values)] = pred_values
            
            if len(pred_values) > 0:
                # Fill remaining with last predicted value
                predictions[len(pred_values):] = pred_values[-1]
            else:
                # No predictions available, use last observed value
                predictions[:] = y_values[-1] if len(y_values) > 0 else 0.0
        
        return predictions

    def _make_tabpfn_prediction_fallback(self, input_data, y_values):
        """
        Enhanced fallback prediction when TabPFN is not available.
        Uses exogenous variables in a simple heuristic.
        """
        try:
            if input_data.shape[1] == 1:
                # Only target variable available
                return self._make_tabpfn_prediction(y_values)
            
            # Enhanced prediction using exogenous variables
            n_features = input_data.shape[1]
            
            if len(y_values) >= 2:
                # Use trend from target and some influence from exogenous variables
                target_trend = y_values[-1] - y_values[-2]
                
                # Simple way to incorporate exogenous influence
                exog_influence = 0.0
                if n_features > 1 and len(input_data) >= 2:
                    # Calculate feature changes
                    recent_exog = input_data[-2:, 1:]  # Last 2 points, exclude target
                    exog_change = np.mean(recent_exog[-1] - recent_exog[-2])
                    exog_influence = exog_change * 0.1  # Small influence factor
                
                # Combine trend with exogenous influence
                adjusted_trend = target_trend + exog_influence
                predictions = [y_values[-1] + adjusted_trend * i for i in range(1, self.h + 1)]
            else:
                predictions = [y_values[-1]] * self.h
            
            return np.array(predictions)
            
        except Exception as e:
            # Final fallback to simple prediction
            return self._make_tabpfn_prediction(y_values)

    def _make_tabpfn_prediction(self, y_values):
        """
        Make prediction using TabPFN for a single time series (target only).
        This is a simplified implementation - in practice, you would use the actual TabPFN API.
        (Kept for backward compatibility and fallback)
        """
        try:
            # Placeholder for actual TabPFN prediction logic
            # In a real implementation, this would interface with the TabPFN model
            
            # For now, use a simple heuristic as placeholder
            if len(y_values) == 0:
                return np.zeros(self.h)
            
            # Simple trend-based prediction as placeholder
            if len(y_values) >= 2:
                trend = y_values[-1] - y_values[-2]
                predictions = [y_values[-1] + trend * i for i in range(1, self.h + 1)]
            else:
                predictions = [y_values[-1]] * self.h
            
            return np.array(predictions)
            
        except Exception as e:
            if self.debug:
                print(f"TabPFN prediction error: {e}")
            # Fallback to naive forecast
            if len(y_values) > 0:
                return np.full(self.h, y_values[-1])
            else:
                return np.zeros(self.h)

    def predict(self, dataset, step_size=1, **data_module_kwargs):
        """
        Use the standard PyTorch Lightning predict workflow for proper cross-validation support.
        This calls the parent BaseModel.predict method which uses predict_step properly.
        """
        if self.debug:
            print(f"TabPFNTS predict: using PyTorch Lightning predict workflow")
            print(f"TabPFNTS predict: dataset.n_groups={dataset.n_groups}")
            print(f"TabPFNTS predict: dataset.indptr={dataset.indptr}")
            print(f"TabPFNTS predict: dataset.temporal.shape={dataset.temporal.shape}")
        
        # Use the parent BaseModel predict method which properly handles cross-validation
        return super().predict(dataset=dataset, step_size=step_size, **data_module_kwargs)

 